package ai.talentify.constants;

public enum SalesUserRoles {
	PRESENTOR, MASTER_TRAINER, CREATIVE_CREATOR, CONTENT_CREATOR, CONTENT_REVIEWER, CREATIVE_ADMIN, CONTENT_ADMIN,
	PANELIST, EXECUTIVE_RECRUITER, RECRUITER, SUPER_ADMIN, COORDINATOR, TRAINER, OWNER, ORG_ADMIN, IT_ADMIN,
	SALES_MANAGER, STUDENT, SALES_ASSOCIATE
}
